In [1]:
import sys
import numpy as np 

In [2]:
# checking the python and numpy lib version
print("sys: {}".format(sys.version))
print("numpy: {}".format(np.__version__))

sys: 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
numpy: 1.19.2


Components of linear algebra are:
    scalar variable,
    vector,
    matrix ,
    tensor,

In [3]:
# declaring a scaler
x = 10
x

10

In [4]:
# vector is an 1D array
y = np.array([1,2,3])
y

array([1, 2, 3])

In [6]:
y = np.arange(9)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
# next is an matrix which is an 2D array
z = np.matrix(([1,2],[3,4])) 
z

matrix([[1, 2],
        [3, 4]])

In [11]:
z = y.reshape((3,3)) #could reshape a 1D array into an matrix
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
# we could create a matrix of all ones and zeros
I = np.ones((2,2))
I

array([[1., 1.],
       [1., 1.]])

In [16]:
type(I[0,0])
# the default values are type is float

numpy.float64

In [18]:
I = np.ones((2,2),dtype=int)
I

array([[1, 1],
       [1, 1]])

In [21]:
# similarly could create matrix for zeros
Z = np.zeros((3,3),dtype = int)
Z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
# Tensor is multi-dimensional and to expand the view beyond 
t = np.ones((3,3,3),dtype=int)
t

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [25]:
# to detremine the paraments
print("tensor shape: {}".format(t.shape))
print("tensor size: {}".format(t.size))

tensor shape: (3, 3, 3)
tensor size: 27


In [31]:
# we could access/manipulate the indexes
t[0,0,1] = 2
t

array([[[1, 2, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [34]:
# matrix operation 
x = np.arange(4)
A = x.reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [37]:
B = np.matrix(([4,5],[6,7]))
B

matrix([[4, 5],
        [6, 7]])

In [38]:
# addition this would be element by element for the size should be same
C = A + B
C

matrix([[ 4,  6],
        [ 8, 10]])

In [40]:
# substraction
B1 = C-A
B1

matrix([[4, 5],
        [6, 7]])

In [43]:
# with multiplication the number of col in the first matrix and the number of rows in 2nd matrix must match
# c(x,y) = a(x,z) * b(z,y)
x = np.arange(10)
A = x.reshape((2,5))
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
y = np.arange(15)
B = y.reshape((5,3))
B

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [54]:
C = np.dot(A,B)
C

array([[ 90, 100, 110],
       [240, 275, 310]])

In [60]:
# matrix transpose
x = A.T
x
# just use the dot with the capital T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])